# Generated by Django 5.1.15 on 2026-10-09 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_name", models.CharField(max_length=120)),
                ("business_name", models.CharField(blank=True, max_length=150)),
                ("bio", models.TextField(blank=True, max_length=1000)),
                ("contact_phone", models.CharField(max_length=30)),
                (
                    "allow_calls",
                    models.BooleanField(
                        default=True, help_text="Show phone call button"
                    ),
                ),
                (
                    "allow_whatsapp",
                    models.BooleanField(
                        default=True, help_text="Show WhatsApp chat link"
                    ),
                ),
                (
                    "allow_messages",
                    models.BooleanField(
                        default=True, help_text="Accept in-platform messages"
                    ),
                ),
                (
                    "allow_email",
                    models.BooleanField(
                        default=False, help_text="Allow direct email inquiry"
                    ),
                ),
                (
                    "location_city",
                    models.CharField(default="Addis Ababa", max_length=100),
                ),
                (
                    "location_neighborhood",
                    models.CharField(blank=True, default="Bole", max_length=100),
                ),
                (
                    "seller_status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Verification Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Verification Rejected"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("total_contact_clicks", models.PositiveIntegerField(default=0)),
                (
                    "response_time_str",
                    models.CharField(
                        default="Typically replies in 1 hour", max_length=50
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "Ethiopian Kebele/National ID"),
                            (
                                "business_license",
                                "Commercial Registration / Business License",
                            ),
                            ("passport", "Passport / Resident ID"),
                        ],
                        default="national_id",
                        max_length=30,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=100)),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="private/verifications/"
                    ),
                ),
                ("seller_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
